{{- if .Values.logstash.esCert.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.logstash.esCert.secretName }}
type: Opaque
data:
  ca.crt: {{ .Values.logstash.esCert.caData | b64enc | quote }}
{{- end }}
